### ISSUE TITLE
empty environment variables cause error

### ISSUE THREAD

**Issue by DomDomHaas** [motdotla/dotenv-expand#26]
Got the following error:

 ERROR  TypeError: Cannot read property 'match' of undefined
TypeError: Cannot read property 'match' of undefined
    at interpolate (D:\EnviDat\Frontend\envidat_frontend\node_modules\dotenv-expand\lib\main.js:10:28)
    at dotenvExpand (D:\EnviDat\Frontend\envidat_frontend\node_modules\dotenv-expand\lib\main.js:54:32)
    at load (D:\EnviDat\Frontend\envidat_frontend\node_modules\@vue\cli-service\lib\Service.js:102:9)
    at Service.loadEnv (D:\EnviDat\Frontend\envidat_frontend\node_modules\@vue\cli-service\lib\Service.js:114:5)
    at Service.init (D:\EnviDat\Frontend\envidat_frontend\node_modules\@vue\cli-service\lib\Service.js:70:10)
    at Service.run (D:\EnviDat\Frontend\envidat_frontend\node_modules\@vue\cli-service\lib\Service.js:209:10)
    at Object.<anonymous> (D:\EnviDat\Frontend\envidat_frontend\node_modules\@vue\cli-service\bin\vue-cli-service.js:36:9)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Function.Module.runMain (module.js:684:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3

I've tested it with the current version like so:
1) cloned the repo
2) npm install
3) npm run test
4) Added additional empty variable in test/.env like so:
BASIC=basic
BASIC_EMPTY=
BASIC_EXPAND=$BASIC
5) npm run test again: 8 of 19 Tests failed.

**Comment by ericrallen** [comment]
Sorry for the delay. Going to take a look at this one and get back to you.

**Comment by jpolvora** [comment]
same issue here.

**Comment by mfaheemakhtar** [comment]
I was thinking to work and fix this. But I'm unable to reproduce. All 19/19 tests are passing with/without the empty variable.

However, test failed because of some leaks.
